- name: Deploy FastAPI Docker App
  hosts: web
  become: yes

  tasks:
    - name: Ensure Docker is installed
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Ensure Docker is running
      service:
        name: docker
        state: started
        enabled: yes

    - name: Copy app folder to target
      copy:
        src: ../app/
        dest: /home/ubuntu/app/
        mode: 0755

    - name: Build Docker image
      command: docker build -t fastapi-app /home/ubuntu/app

    - name: Run Docker container
      command: docker run -d -p 5000:5000 --name fastapi-app fastapi-app
      ignore_errors: yes  # In case it was already running

    - name: Remove old container if needed
      command: docker rm -f fastapi-app
      when: ansible_failed_result is defined
      ignore_errors: yes

    - name: Re-run Docker container
      command: docker run -d -p 5000:5000 --name fastapi-app fastapi-app
      when: ansible_failed_result is defined

