name: Deploy to EC2 via Ansible

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy app code to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@65.0.173.169 'rm -rf ~/app && mkdir ~/app'
        scp -o StrictHostKeyChecking=no -r ./app ubuntu@65.0.173.169:~/app

    - name: Copy Ansible files to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@65.0.173.169 'rm -rf ~/ansible && mkdir ~/ansible'
        scp -o StrictHostKeyChecking=no -r ./ansible/* ubuntu@65.0.173.169:~/ansible/

    - name: Run Ansible Playbook on EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@65.0.173.169 'cd ~/ansible && ansible-playbook -i inventory.ini playbook.yml'
