name: Deploy to EC2 via Ansible

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Copy code to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@<EC2-IP> 'rm -rf ~/app && mkdir ~/app'
        scp -o StrictHostKeyChecking=no -r ./app ubuntu@<EC2-IP>:~/app

    - name: Run Ansible Playbook
      run: |
        scp -o StrictHostKeyChecking=no -r ./ansible ubuntu@<EC2-IP>:~/ansible
        ssh -o StrictHostKeyChecking=no ubuntu@<EC2-IP> 'cd ~/ansible && ansible-playbook -i inventory.ini playbook.yml'
